#!/bin/bash
echo "Just don't look inside this script, it's totaly awful!!!!"
sleep 10
echo "Let's begin"
sleep 10
echo "Some prerarations before we started"
rm -rfv /home/lvv/.ssh/known_hosts
/usr/bin/chmod 600 /home/lvv/.ssh/id_rsa.pub
/usr/bin/chmod 600 home/lvv/.ssh/id_rsa
echo "Setting nuls to ansible inventory file"
/usr/bin/cat /dev/null > home/lvv//Documents/projects/Skills/ansibles/inventory.cfg 
cd /home/lbb/Documents/projects/Skills/terraforms
sleep 10
echo "Performing terraform ..."
/usr/bin/terraform apply -auto-approve
/usr/bin/terraform apply -auto-approve
/usr/bin/terraform apply -auto-approve
echo "Terraforming complete"
sleep 10
echo "Now let's do some magic!!!"
echo "[web]" >> /home/lvv/Documents/projects/Skills/ansibles/inventory.cfg 
/usr/bin/terraform putput | grep web | sed s/\"//g >> /home/lvv/Documents/projects/Skills/ansibles/inventory.cfg
#/usr/bin/terraform output | grep web | awk {'print $3'} | sed s/\"//g >> home/lvv/Documents/projects/Skills/ansibles/inventory.cfg
echo "[app]" >> /home/lvv/Documents/projects/Skills/ansibles/inventory.cfg 
/usr/bin/terraform putput | grep app | sed s/\"//g >> /home/lvv/Documents/projects/Skills/ansibles/inventory.cfg
#/usr/bin/terraform output | grep app | awk {'print $3'} | sed s/\"//g >> /home/lvv/Documents/projects/Skills/ansibles/inventory.cfg
echo "[balancer]" >> /home/lvv/Documents/projects/Skills/ansibles/inventory.cfg 
/usr/bin/terraform putput | grep balancer | sed s/\"//g  >> /home/lvv/Documents/projects/Skills/ansibles/inventory.cfg
#/usr/bin/terraform output | grep balancer | awk {'print $3'} | sed s/\"//g >> /home/lvv/Documents/projects/Skills/ansibles/inventory.cfg 
sed s/' '//g -i /home/lvv/Documents/projects/Skills/ansibles/inventory.cfg
echo "Magic done, and you even didn't see it ((("
sleep 10
echo "Let's start another magic tricks"
echo "Applying ansible to our servers"
cd /home/lvv/Documents/projects/Skills/ansibles/
/usr/local/bin/ansible-playbook -i /home/lvv/Documents/projects/Skills/ansibles/inventory.cfg /home/lvv/Documents/projects/Skills/ansibles/web.yml
/usr/local/bin/ansible-playbook -i /home/lvv/Documents/projects/Skills/ansibles/inventory.cfg /home/lvv/Documents/projects/Skills/ansibles/app.yml
sleep 10
echo "Ansible completed"
sleep 10
